// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZaPqHPtkloby0balZg81UwURDFCwc-W8',
    appId: '1:593163433187:web:57df8e0afd8fa37c3381d6',
    messagingSenderId: '593163433187',
    projectId: 'chittoo-bf414',
    authDomain: 'chittoo-bf414.firebaseapp.com',
    storageBucket: 'chittoo-bf414.firebasestorage.app',
    measurementId: 'G-F8JVSDS5NS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9EJJT9RVsReAGzUo6osRwgyEO_YQKol4',
    appId: '1:593163433187:android:2770b210748419553381d6',
    messagingSenderId: '593163433187',
    projectId: 'chittoo-bf414',
    storageBucket: 'chittoo-bf414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ExQpCM4NfSqJf6fZgP8moudZED-hQSg',
    appId: '1:593163433187:ios:511c6542d14ad4633381d6',
    messagingSenderId: '593163433187',
    projectId: 'chittoo-bf414',
    storageBucket: 'chittoo-bf414.firebasestorage.app',
    iosBundleId: 'com.example.chittoo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ExQpCM4NfSqJf6fZgP8moudZED-hQSg',
    appId: '1:593163433187:ios:511c6542d14ad4633381d6',
    messagingSenderId: '593163433187',
    projectId: 'chittoo-bf414',
    storageBucket: 'chittoo-bf414.firebasestorage.app',
    iosBundleId: 'com.example.chittoo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZaPqHPtkloby0balZg81UwURDFCwc-W8',
    appId: '1:593163433187:web:0a375a14258f60273381d6',
    messagingSenderId: '593163433187',
    projectId: 'chittoo-bf414',
    authDomain: 'chittoo-bf414.firebaseapp.com',
    storageBucket: 'chittoo-bf414.firebasestorage.app',
    measurementId: 'G-3DG3TP6QEC',
  );

}